#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 12, 2020 03:52:49 PM +0700  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Add_employee_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Add_employee_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Add_employee_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("300x300+698+201")
        top.minsize(116, 1)
        top.maxsize(1364, 750)
        top.resizable(0, 0)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.0, rely=0.033, height=21, width=104)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''ADD EMPLOYEE''')
        tooltip_font = "TkDefaultFont"
        ToolTip(self.Label1, tooltip_font, '''ADD EMPLOYEE''', delay=0.5)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.033, rely=0.167, height=21, width=74)
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''ID Number''')

        self.Label2_1 = tk.Label(top)
        self.Label2_1.place(relx=0.033, rely=0.267, height=21, width=74)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Name''')

        self.Label2_2 = tk.Label(top)
        self.Label2_2.place(relx=0.033, rely=0.367, height=21, width=74)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(anchor='w')
        self.Label2_2.configure(background="#d9d9d9")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''Department''')

        self.Label2_3 = tk.Label(top)
        self.Label2_3.place(relx=0.033, rely=0.467, height=21, width=74)
        self.Label2_3.configure(activebackground="#f9f9f9")
        self.Label2_3.configure(activeforeground="black")
        self.Label2_3.configure(anchor='w')
        self.Label2_3.configure(background="#d9d9d9")
        self.Label2_3.configure(disabledforeground="#a3a3a3")
        self.Label2_3.configure(foreground="#000000")
        self.Label2_3.configure(highlightbackground="#d9d9d9")
        self.Label2_3.configure(highlightcolor="black")
        self.Label2_3.configure(text='''Salary Hour''')

        self.Label2_4 = tk.Label(top)
        self.Label2_4.place(relx=0.033, rely=0.567, height=21, width=74)
        self.Label2_4.configure(activebackground="#f9f9f9")
        self.Label2_4.configure(activeforeground="black")
        self.Label2_4.configure(anchor='w')
        self.Label2_4.configure(background="#d9d9d9")
        self.Label2_4.configure(disabledforeground="#a3a3a3")
        self.Label2_4.configure(foreground="#000000")
        self.Label2_4.configure(highlightbackground="#d9d9d9")
        self.Label2_4.configure(highlightcolor="black")
        self.Label2_4.configure(text='''Work Hour''')

        self.Label2_5 = tk.Label(top)
        self.Label2_5.place(relx=0.033, rely=0.667, height=21, width=74)
        self.Label2_5.configure(activebackground="#f9f9f9")
        self.Label2_5.configure(activeforeground="black")
        self.Label2_5.configure(anchor='w')
        self.Label2_5.configure(background="#d9d9d9")
        self.Label2_5.configure(cursor="fleur")
        self.Label2_5.configure(disabledforeground="#a3a3a3")
        self.Label2_5.configure(foreground="#000000")
        self.Label2_5.configure(highlightbackground="#d9d9d9")
        self.Label2_5.configure(highlightcolor="black")
        self.Label2_5.configure(text='''Total Salary''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.367, rely=0.167,height=20, relwidth=0.58)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry1_6 = tk.Entry(top)
        self.Entry1_6.place(relx=0.367, rely=0.267,height=20, relwidth=0.58)
        self.Entry1_6.configure(background="white")
        self.Entry1_6.configure(disabledforeground="#a3a3a3")
        self.Entry1_6.configure(font="TkFixedFont")
        self.Entry1_6.configure(foreground="#000000")
        self.Entry1_6.configure(highlightbackground="#d9d9d9")
        self.Entry1_6.configure(highlightcolor="black")
        self.Entry1_6.configure(insertbackground="black")
        self.Entry1_6.configure(selectbackground="#c4c4c4")
        self.Entry1_6.configure(selectforeground="black")

        self.Entry1_7 = tk.Entry(top)
        self.Entry1_7.place(relx=0.367, rely=0.367,height=20, relwidth=0.58)
        self.Entry1_7.configure(background="white")
        self.Entry1_7.configure(disabledforeground="#a3a3a3")
        self.Entry1_7.configure(font="TkFixedFont")
        self.Entry1_7.configure(foreground="#000000")
        self.Entry1_7.configure(highlightbackground="#d9d9d9")
        self.Entry1_7.configure(highlightcolor="black")
        self.Entry1_7.configure(insertbackground="black")
        self.Entry1_7.configure(selectbackground="#c4c4c4")
        self.Entry1_7.configure(selectforeground="black")

        self.Entry1_8 = tk.Entry(top)
        self.Entry1_8.place(relx=0.367, rely=0.467,height=20, relwidth=0.58)
        self.Entry1_8.configure(background="white")
        self.Entry1_8.configure(disabledforeground="#a3a3a3")
        self.Entry1_8.configure(font="TkFixedFont")
        self.Entry1_8.configure(foreground="#000000")
        self.Entry1_8.configure(highlightbackground="#d9d9d9")
        self.Entry1_8.configure(highlightcolor="black")
        self.Entry1_8.configure(insertbackground="black")
        self.Entry1_8.configure(selectbackground="#c4c4c4")
        self.Entry1_8.configure(selectforeground="black")

        self.Entry1_9 = tk.Entry(top)
        self.Entry1_9.place(relx=0.367, rely=0.567,height=20, relwidth=0.58)
        self.Entry1_9.configure(background="white")
        self.Entry1_9.configure(disabledforeground="#a3a3a3")
        self.Entry1_9.configure(font="TkFixedFont")
        self.Entry1_9.configure(foreground="#000000")
        self.Entry1_9.configure(highlightbackground="#d9d9d9")
        self.Entry1_9.configure(highlightcolor="black")
        self.Entry1_9.configure(insertbackground="black")
        self.Entry1_9.configure(selectbackground="#c4c4c4")
        self.Entry1_9.configure(selectforeground="black")

        self.Entry1_10 = tk.Entry(top)
        self.Entry1_10.place(relx=0.367, rely=0.667,height=20, relwidth=0.58)
        self.Entry1_10.configure(background="white")
        self.Entry1_10.configure(disabledforeground="#a3a3a3")
        self.Entry1_10.configure(font="TkFixedFont")
        self.Entry1_10.configure(foreground="#000000")
        self.Entry1_10.configure(highlightbackground="#d9d9d9")
        self.Entry1_10.configure(highlightcolor="black")
        self.Entry1_10.configure(insertbackground="black")
        self.Entry1_10.configure(selectbackground="#c4c4c4")
        self.Entry1_10.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.367, rely=0.8, height=24, width=77)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=Add_employee_support.add_employee)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Save''')

# ======================================================
# Modified by Rozen to remove Tkinter import statements and to receive
# the font as an argument.
# ======================================================
# Found the original code at:
# http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
# ======================================================

from time import time, localtime, strftime

class ToolTip(tk.Toplevel):
    """
    Provides a ToolTip widget for Tkinter.
    To apply a ToolTip to any Tkinter widget, simply pass the widget to the
    ToolTip constructor
    """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=1, follow=True):
        """
        Initialize the ToolTip

        Arguments:
          wdgt: The widget this ToolTip is assigned to
          tooltip_font: Font to be used
          msg:  A static string message assigned to the ToolTip
          msgFunc: A function that retrieves a string to use as the ToolTip text
          delay:   The delay in seconds before the ToolTip appears(may be float)
          follow:  If True, the ToolTip follows motion, otherwise hides
        """
        self.wdgt = wdgt
        # The parent of the ToolTip is the parent of the ToolTips widget
        self.parent = self.wdgt.master
        # Initalise the Toplevel
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        # Hide initially
        self.withdraw()
        # The ToolTip Toplevel should have no frame or title bar
        self.overrideredirect(True)

        # The msgVar will contain the text displayed by the ToolTip
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        # The text of the ToolTip is displayed in a Message widget
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()

        # Add bindings to the widget.  This will NOT override
        # bindings that the widget already has
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')

    def spawn(self, event=None):
        """
        Spawn the ToolTip.  This simply makes the ToolTip eligible for display.
        Usually this is caused by entering the widget

        Arguments:
          event: The event that called this funciton
        """
        self.visible = 1
        # The after function takes a time argument in miliseconds
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        """
        Displays the ToolTip if the time delay has been long enough
        """
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        """
        Processes motion within the widget.
        Arguments:
          event: The event that called this function
        """
        self.lastMotion = time()
        # If the follow flag is not set, motion within the
        # widget will make the ToolTip disappear
        #
        if self.follow is False:
            self.withdraw()
            self.visible = 1

        # Offset the ToolTip 10x10 pixes southwest of the pointer
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            # Try to call the message function.  Will not change
            # the message if the message function is None or
            # the message function fails
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        """
        Hides the ToolTip.  Usually this is caused by leaving the widget
        Arguments:
          event: The event that called this function
        """
        self.visible = 0
        self.withdraw()

# ===========================================================
#                   End of Class ToolTip
# ===========================================================

if __name__ == '__main__':
    vp_start_gui()





