#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 11, 2020 04:30:47 PM +0700  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Manager_Page_support
import TimeClockPage
import time
import Manager
import Employee

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    root.title("Manager Page | Easy Time Clock")
    root.wm_iconbitmap('icon.ico')
    top = Toplevel1 (root)
    Manager_Page_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Manager_Page_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None
    

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Arial} -size 12"
        font11 = "-family {Arial} -size 14"
        font12 = "-family {Arial} -size 9"
        font9 = "-family {Arial} -size 18 -weight bold"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+467+108")
        top.minsize(116, 1)
        top.maxsize(1364, 750)
        top.resizable(1, 1)
        top.title("Manager Page | Easy Time Clock")
        top.configure(background="#d9d9d9")

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(0, text="Home",compound="left",underline="-1",)
        self.TNotebook1_t1.configure(background="#d9d9d9")
        self.TNotebook1_t1.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t1.configure(highlightcolor="black")
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(1, text="Clock Schedule", compound="left"
                ,underline="-1", )
        self.TNotebook1_t2.configure(background="#d9d9d9")
        self.TNotebook1_t2.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t2.configure(highlightcolor="black")
        self.TNotebook1_t3 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t3, padding=3)
        self.TNotebook1.tab(2, text="My Employee", compound="none", underline="-1"
                ,)
        self.TNotebook1_t3.configure(background="#d9d9d9")
        self.TNotebook1_t3.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t3.configure(highlightcolor="black")
        self.TNotebook1_t4 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t4, padding=3)
        self.TNotebook1.tab(3, text="Report",compound="none",underline="-1",)
        self.TNotebook1_t4.configure(background="#d9d9d9")
        self.TNotebook1_t4.configure(highlightbackground="#d9d9d9")
        self.TNotebook1_t4.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.TNotebook1_t1)
        self.Label1.place(relx=0.034, rely=0.024, height=41, width=124)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Welcome,''')

        self.FillByUsername = tk.Label(self.TNotebook1_t1)
        self.FillByUsername.place(relx=0.034, rely=0.118, height=21, width=144)
        self.FillByUsername.configure(activebackground="#f9f9f9")
        self.FillByUsername.configure(activeforeground="black")
        self.FillByUsername.configure(anchor='w')
        self.FillByUsername.configure(background="#d9d9d9")
        self.FillByUsername.configure(disabledforeground="#a3a3a3")
        self.FillByUsername.configure(font=font10)
        self.FillByUsername.configure(foreground="#000000")
        self.FillByUsername.configure(highlightbackground="#d9d9d9")
        self.FillByUsername.configure(highlightcolor="black")
        self.FillByUsername.configure(text="<<username>>")

        self.FillByDepartment = tk.Label(self.TNotebook1_t1)
        self.FillByDepartment.place(relx=0.034, rely=0.165, height=21, width=144)

        self.FillByDepartment.configure(activebackground="#f9f9f9")
        self.FillByDepartment.configure(activeforeground="black")
        self.FillByDepartment.configure(anchor='w')
        self.FillByDepartment.configure(background="#d9d9d9")
        self.FillByDepartment.configure(disabledforeground="#a3a3a3")
        self.FillByDepartment.configure(font="-family {Arial} -size 12")
        self.FillByDepartment.configure(foreground="#000000")
        self.FillByDepartment.configure(highlightbackground="#d9d9d9")
        self.FillByDepartment.configure(highlightcolor="black")
        self.FillByDepartment.configure(text="<<Department>>")

        self.Label1_3 = tk.Label(self.TNotebook1_t1)
        self.Label1_3.place(relx=0.034, rely=0.283, height=41, width=124)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(anchor='w')
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font=font11)
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''Today Date''')

        self.Label1_4 = tk.Label(self.TNotebook1_t1)
        self.Label1_4.place(relx=0.034, rely=0.377, height=41, width=144)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(anchor='w')
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Arial} -size 14")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Clock In Time''')

        self.Label1_4 = tk.Label(self.TNotebook1_t1)
        self.Label1_4.place(relx=0.034, rely=0.448, height=41, width=144)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(anchor='w')
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Arial} -size 14")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Clock Out Time''')

        self.Label1_4 = tk.Label(self.TNotebook1_t1)
        self.Label1_4.place(relx=0.403, rely=0.283, height=41, width=14)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(anchor='w')
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Arial} -size 14")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text=''':''')

        self.Label1_5 = tk.Label(self.TNotebook1_t1)
        self.Label1_5.place(relx=0.403, rely=0.448, height=41, width=14)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(anchor='w')
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Arial} -size 14")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text=''':''')

        self.time2 = time.strftime('%d/%m/20%y')

        self.FillByTodayDate = tk.Label(self.TNotebook1_t1)
        self.FillByTodayDate.place(relx=0.436, rely=0.283, height=41, width=124)
        self.FillByTodayDate.configure(activebackground="#f9f9f9")
        self.FillByTodayDate.configure(activeforeground="black")
        self.FillByTodayDate.configure(anchor='w')
        self.FillByTodayDate.configure(background="#d9d9d9")
        self.FillByTodayDate.configure(disabledforeground="#a3a3a3")
        self.FillByTodayDate.configure(font="-family {Arial} -size 14")
        self.FillByTodayDate.configure(foreground="#000000")
        self.FillByTodayDate.configure(highlightbackground="#d9d9d9")
        self.FillByTodayDate.configure(highlightcolor="black")
        self.FillByTodayDate.configure(text=self.time2)

        self.FillClockIn = tk.Label(self.TNotebook1_t1)
        self.FillClockIn.place(relx=0.436, rely=0.377, height=41, width=124)
        self.FillClockIn.configure(activebackground="#f9f9f9")
        self.FillClockIn.configure(activeforeground="black")
        self.FillClockIn.configure(anchor='w')
        self.FillClockIn.configure(background="#d9d9d9")
        self.FillClockIn.configure(disabledforeground="#a3a3a3")
        self.FillClockIn.configure(font="-family {Arial} -size 14")
        self.FillClockIn.configure(foreground="#000000")
        self.FillClockIn.configure(highlightbackground="#d9d9d9")
        self.FillClockIn.configure(highlightcolor="black")
        self.FillClockIn.configure(text='''07:00:00''')

        self.FillClockOut = tk.Label(self.TNotebook1_t1)
        self.FillClockOut.place(relx=0.436, rely=0.448, height=41, width=124)
        self.FillClockOut.configure(activebackground="#f9f9f9")
        self.FillClockOut.configure(activeforeground="black")
        self.FillClockOut.configure(anchor='w')
        self.FillClockOut.configure(background="#d9d9d9")
        self.FillClockOut.configure(disabledforeground="#a3a3a3")
        self.FillClockOut.configure(font="-family {Arial} -size 14")
        self.FillClockOut.configure(foreground="#000000")
        self.FillClockOut.configure(highlightbackground="#d9d9d9")
        self.FillClockOut.configure(highlightcolor="black")
        self.FillClockOut.configure(text='''15:00:00''')

        self.StartTimeClock = ttk.Button(self.TNotebook1_t1, command=next_page)
        self.StartTimeClock.place(relx=0.688, rely=0.755, height=45, width=126)
        self.StartTimeClock.configure(takefocus="")
        self.StartTimeClock.configure(text='''Start Time Clock''')

        self.Label1_5 = tk.Label(self.TNotebook1_t1)
        self.Label1_5.place(relx=0.403, rely=0.377, height=41, width=14)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(anchor='w')
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Arial} -size 14")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text=''':''')

        self.Label1_5 = tk.Label(self.TNotebook1_t2)
        self.Label1_5.place(relx=0.034, rely=0.047, height=41, width=124)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(anchor='w')
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Arial} -size 18 -weight bold")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text='''Schedule''')

        self.Label1_4 = tk.Label(self.TNotebook1_t2)
        self.Label1_4.place(relx=0.067, rely=0.377, height=41, width=144)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(anchor='w')
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Arial} -size 14")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Clock In Time''')

        self.Label1_5 = tk.Label(self.TNotebook1_t2)
        self.Label1_5.place(relx=0.067, rely=0.448, height=41, width=144)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(anchor='w')
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Arial} -size 14")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text='''Clock Out Time''')

        self.Label1_6 = tk.Label(self.TNotebook1_t2)
        self.Label1_6.place(relx=0.403, rely=0.448, height=41, width=14)
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(anchor='w')
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(font="-family {Arial} -size 14")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(text=''':''')

        self.ScheduleEntryIn = tk.Entry(self.TNotebook1_t2)
        self.ScheduleEntryIn.place(relx=0.453, rely=0.401, height=20
                , relwidth=0.242)
        self.ScheduleEntryIn.configure(background="white")
        self.ScheduleEntryIn.configure(disabledforeground="#a3a3a3")
        self.ScheduleEntryIn.configure(font="TkFixedFont")
        self.ScheduleEntryIn.configure(foreground="#000000")
        self.ScheduleEntryIn.configure(insertbackground="black")

        self.ScheduleEntryOut = tk.Entry(self.TNotebook1_t2)
        self.ScheduleEntryOut.place(relx=0.453, rely=0.472, height=20
                , relwidth=0.242)
        self.ScheduleEntryOut.configure(background="white")
        self.ScheduleEntryOut.configure(disabledforeground="#a3a3a3")
        self.ScheduleEntryOut.configure(font="TkFixedFont")
        self.ScheduleEntryOut.configure(foreground="#000000")
        self.ScheduleEntryOut.configure(highlightbackground="#d9d9d9")
        self.ScheduleEntryOut.configure(highlightcolor="black")
        self.ScheduleEntryOut.configure(insertbackground="black")
        self.ScheduleEntryOut.configure(selectbackground="#c4c4c4")
        self.ScheduleEntryOut.configure(selectforeground="black")

        self.ScheduleButtonSave = ttk.Button(self.TNotebook1_t2)
        self.ScheduleButtonSave.place(relx=0.084, rely=0.802, height=25
                , width=76)
        self.ScheduleButtonSave.configure(takefocus="")
        self.ScheduleButtonSave.configure(text='''Save''')
        self.ScheduleButtonSave.configure(cursor="fleur")

        self.Label1_7 = tk.Label(self.TNotebook1_t2)
        self.Label1_7.place(relx=0.403, rely=0.377, height=41, width=14)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(anchor='w')
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Arial} -size 14")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text=''':''')

        self.Text1 = tk.Text(self.TNotebook1_t3)
        self.Text1.place(relx=0.017, rely=0.024, relheight=0.67, relwidth=0.963)
        self.Text1.configure(background="white")
        self.Text1.configure(font=font12)
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")
        self.Text1.delete(1.0, tk.END)
        self.Text1.insert(tk.END, MyEmployeelist())

        self.TButton3 = ttk.Button(self.TNotebook1_t3)
        self.TButton3.place(relx=0.772, rely=0.731, height=25, width=76)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Add New''', command=add_new)

        self.Text1_8 = tk.Text(self.TNotebook1_t4)
        self.Text1_8.place(relx=0.017, rely=0.024, relheight=0.67
                , relwidth=0.963)
        self.Text1_8.configure(background="white")
        self.Text1_8.configure(font="-family {Arial} -size 9")
        self.Text1_8.configure(foreground="black")
        self.Text1_8.configure(highlightbackground="#d9d9d9")
        self.Text1_8.configure(highlightcolor="black")
        self.Text1_8.configure(insertbackground="black")
        self.Text1_8.configure(selectbackground="#c4c4c4")
        self.Text1_8.configure(selectforeground="black")
        self.Text1_8.configure(wrap="word")

def next_page():
    TimeClockPage.create_Toplevel1(root)

def add_new():
    import Add_employee
    Add_employee.create_Toplevel1(root)

def MyEmployeelist():
    toText = "ID Num\t| Name\t\t| Department\t| Salary\t| WorkHour\t| TotalSalary\n"
    listEmployee = Employee.Employee.list_Employee
    for i in range(len(listEmployee)):
        toText = toText + str(listEmployee[i].getID())+"\t| "+str(listEmployee[i].getName())+"\t\t| "+str(listEmployee[i].getDepartment())+"\t| "+str(listEmployee[i].getSalaryHour())+"\t | "+str(listEmployee[i].getWorkHour())+"\t | "+str(listEmployee[i].getTotalSalary())+"\t\n"
    return toText


if __name__ == '__main__':
    vp_start_gui()





